version: "3.7"
#  http://localhost:8098/
services:
    nginx:
      build:
        context: .
        dockerfile: docker/nginx/Dockerfile
      ports:
        - 8097:80
      links:
        - fpm
      volumes:
        - ./:/var/www/forum
    fpm:
      build:
        context: .
        dockerfile: docker/fpm/Dockerfile
      volumes:
        - ./:/var/www/forum
      links:
        - mysql
    mysql:
      image: mysql:5.7
      ports:
        - 33062:3306
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=forum

