<?php

namespace Tests\Feature;
use App\Reply;
use App\Thread;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;

class ReadThreadsTest extends TestCase
{
//    use DatabaseMigrations;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->thread = factory(Thread::class)->create();
    }

    /**
     * @Threads
     */
    public function test_a_user_can_view_all_threads()
    {
        #step2
        $response = $this->get('/threads')
            ->assertSee($this->thread->title);
//        $response->assertStatus(200);
    }
    public function test_a_user_can_read_a_single_threads()
    {
        #step2
        $this->get($this->thread->path())
            ->assertSee($this->thread->title);
    }
    public function test_a_user_can_read_replies_that_are_associated_with_a_thread()
    {
        #step3
        $reply = factory(Reply::class)
            ->create(['thread_id' => $this->thread->id]);

        $this->get($this->thread->path())
            ->assertSee($reply->body);

    }
}
