<?php


use App\Channel;
use App\Thread;
use App\User;
use Tests\TestCase;

class ThreadsTest extends TestCase{

    protected $thread;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->thread = factory(Thread::class)->create();
    }

    function test_thread_has_replies(){
        $this->assertInstanceOf('Illuminate\Database\Eloquent\Collection', $this->thread->replies);
    }

    function test_thread_has_a_creator()
    {
        $this->assertInstanceOf(User::class, $this->thread->creator);
    }

    function test_a_thread_can_add_a_reply(){
        $this->thread->addReply([
           'body' => 'Foobar',
            'user_id' => 1
        ]);

        $this->assertCount(1, $this->thread->replies);
    }
    function test_a_thread_belongs_to_a_channel(){
        $thread = create(Thread::class);
        $this->assertInstanceOf(Channel::class, $thread->channel);
        $thread->channel;
    }
}
